"""Removed columns and added new columns to usage table.

Revision ID: 1e12f19b4102
Revises: 9828d3913d9f
Create Date: 2026-10-01 11:48:19.848605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e12f19b4102'
down_revision: Union[str, Sequence[str], None] = '9828d3913d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('total_file_size', sa.Float(), nullable=True))
    op.add_column('usage', sa.Column('summary_amount', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('usage_user_id_fkey'), 'usage', type_='foreignkey')
    op.create_foreign_key(None, 'usage', 'user_account', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage', 'password')
    op.drop_column('usage', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'usage', type_='foreignkey')
    op.create_foreign_key(op.f('usage_user_id_fkey'), 'usage', 'user_account', ['user_id'], ['id'])
    op.drop_column('usage', 'summary_amount')
    op.drop_column('usage', 'total_file_size')
    # ### end Alembic commands ###
